# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6441a6f5ff774c46223c231a25d39f9b08e34cc3ee99917a50ee707396ec23cee2e45b043948f79dcfba4a2aa91bd0831f673d9aa49af5b8045d4d7ec3e9a279

test:
  secret_key_base: a5b8e7ec49754a5f00fc9ffdacdd7c9ec1661af04ee3fb32ebd6e2e5fccf45ffd5eff2eae5f79e59bd6660ff8bee910db9e227d66da5b29b9045b42e9616c98b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
